global:
  domain: c-39b7f17.stage.kyma.ondemand.com
  imagePullSecret:
    name: container-registry
srv:
  bindings:
    db:
      fromSecret: cpapp-schema-binding
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: dewdale/cpapp-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
hana-deployer:
  image:
    repository: dewdale/cpapp-hana-deployer
    tag: latest
  bindings:
    hana:
      fromSecret: cpapp-schema-binding
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: cpapp-kyma
    tenant-mode: dedicated
